# Generated by Django 5.2.7 on 2025-10-14 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
            ],
        ),
    ]
