# Generated by Django 5.2.7 on 2025-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Claimed', 'Claimed')], default='Pending', max_length=20),
        ),
    ]
